services:

  app:
    build: 
      context: .
      target: production
    container_name: payments-subs-api
    ports:
      - "9880:9880"     
    volumes:
      # - .:/app                       # Map local code to container
      # - /app/node_modules            # Anonymous volume to protect container's node_modules
      - ./logs/:/app/logs
    env_file:
      - ${ENV_PATH:-./.env}
    depends_on:
      - postgres-db_payments-subs-api
    networks:
      - payments-subs-api-net
  postgres-db_payments-subs-api:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ${ENV_PATH:-./.env}
    ports:
      - "5491:5432"
    volumes:
      - ./api-payments-subs_db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payments-subs-api-net


networks:
  payments-subs-api-net:
    external: true
    name: shared-crud-api-network
    # driver: bridge